In [1]:
from bs4 import BeautifulSoup
import requests
import csv

import pandas as pd
import re

In [2]:
url = 'https://www.imdb.com/chart/top/'

In [4]:
html_text = requests.get(url).text

In [5]:
soup = BeautifulSoup(html_text, 'lxml')

In [6]:
names = soup.find_all('td', class_ = 'titleColumn')
names

[<td class="titleColumn">
       1.
       <a href="/title/tt0111161/" title="Frank Darabont (dir.), Tim Robbins, Morgan Freeman">The Shawshank Redemption</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       2.
       <a href="/title/tt0068646/" title="Francis Ford Coppola (dir.), Marlon Brando, Al Pacino">The Godfather</a>
 <span class="secondaryInfo">(1972)</span>
 </td>,
 <td class="titleColumn">
       3.
       <a href="/title/tt0468569/" title="Christopher Nolan (dir.), Christian Bale, Heath Ledger">The Dark Knight</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       4.
       <a href="/title/tt0071562/" title="Francis Ford Coppola (dir.), Al Pacino, Robert De Niro">The Godfather Part II</a>
 <span class="secondaryInfo">(1974)</span>
 </td>,
 <td class="titleColumn">
       5.
       <a href="/title/tt0050083/" title="Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb">12 Angry Men</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       6.
       <a href="/title/tt0108052/" title="Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes">Schindler's List</a>
 <span class="secondaryInfo">(1993)</span>
 </td>,
 <td class="titleColumn">
       7.
       <a href="/title/tt0167260/" title="Peter Jackson (dir.), Elijah Wood, Viggo Mortensen">The Lord of the Rings: The Return of the King</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       8.
       <a href="/title/tt0110912/" title="Quentin Tarantino (dir.), John Travolta, Uma Thurman">Pulp Fiction</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       9.
       <a href="/title/tt0120737/" title="Peter Jackson (dir.), Elijah Wood, Ian McKellen">The Lord of the Rings: The Fellowship of the Ring</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       10.
       <a href="/title/tt0060196/" title="Sergio Leone (dir.), Clint Eastwood, Eli Wallach">Il buono, il brutto, il cattivo</a>
 <span class="secondaryInfo">(1966)</span>
 </td>,
 <td class="titleColumn">
       11.
       <a href="/title/tt0109830/" title="Robert Zemeckis (dir.), Tom Hanks, Robin Wright">Forrest Gump</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       12.
       <a href="/title/tt0137523/" title="David Fincher (dir.), Brad Pitt, Edward Norton">Fight Club</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       13.
       <a href="/title/tt0167261/" title="Peter Jackson (dir.), Elijah Wood, Ian McKellen">The Lord of the Rings: The Two Towers</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       14.
       <a href="/title/tt1375666/" title="Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt">Inception</a>
 <span class="secondaryInfo">(2010)</span>
 </td>,
 <td class="titleColumn">
       15.
       <a href="/title/tt0080684/" title="Irvin Kershner (dir.), Mark Hamill, Harrison Ford">The Empire Strikes Back</a>
 <span class="secondaryInfo">(1980)</span>
 </td>,
 <td class="titleColumn">
       16.
       <a href="/title/tt0133093/" title="Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne">The Matrix</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       17.
       <a href="/title/tt0099685/" title="Martin Scorsese (dir.), Robert De Niro, Ray Liotta">GoodFellas</a>
 <span class="secondaryInfo">(1990)</span>
 </td>,
 <td class="titleColumn">
       18.
       <a href="/title/tt0073486/" title="Milos Forman (dir.), Jack Nicholson, Louise Fletcher">One Flew Over the Cuckoo's Nest</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       19.
       <a href="/title/tt0114369/" title="David Fincher (dir.), Morgan Freeman, Brad Pitt">Se7en</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       20.
       <a href="/title/tt0047478/" title="Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura">Shichinin no samurai</a>
 <span class="secondaryInfo">(1954)</span>
 </td>,
 <td class="titleColumn">
       21.
       <a href="/title/tt0038650/" title="Frank Capra (dir.), James Stewart, Donna Reed">It's a Wonderful Life</a>
 <span class="secondaryInfo">(1946)</span>
 </td>,
 <td class="titleColumn">
       22.
       <a href="/title/tt0102926/" title="Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins">The Silence of the Lambs</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       23.
       <a href="/title/tt0120815/" title="Steven Spielberg (dir.), Tom Hanks, Matt Damon">Saving Private Ryan</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       24.
       <a href="/title/tt0317248/" title="Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino">Cidade de Deus</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       25.
       <a href="/title/tt0816692/" title="Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway">Interstellar</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       26.
       <a href="/title/tt0118799/" title="Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi">La vita è bella</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       27.
       <a href="/title/tt0120689/" title="Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan">The Green Mile</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       28.
       <a href="/title/tt0076759/" title="George Lucas (dir.), Mark Hamill, Harrison Ford">Star Wars</a>
 <span class="secondaryInfo">(1977)</span>
 </td>,
 <td class="titleColumn">
       29.
       <a href="/title/tt0103064/" title="James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton">Terminator 2: Judgment Day</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       30.
       <a href="/title/tt0088763/" title="Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd">Back to the Future</a>
 <span class="secondaryInfo">(1985)</span>
 </td>,
 <td class="titleColumn">
       31.
       <a href="/title/tt0245429/" title="Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette">Sen to Chihiro no kamikakushi</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       32.
       <a href="/title/tt0253474/" title="Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann">The Pianist</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       33.
       <a href="/title/tt0054215/" title="Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh">Psycho</a>
 <span class="secondaryInfo">(1960)</span>
 </td>,
 <td class="titleColumn">
       34.
       <a href="/title/tt6751668/" title="Bong Joon Ho (dir.), Song Kang-ho, Lee Sun-kyun">Gisaengchung</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       35.
       <a href="/title/tt0110413/" title="Luc Besson (dir.), Jean Reno, Gary Oldman">Léon</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       36.
       <a href="/title/tt0110357/" title="Roger Allers (dir.), Matthew Broderick, Jeremy Irons">The Lion King</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       37.
       <a href="/title/tt0172495/" title="Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix">Gladiator</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       38.
       <a href="/title/tt0120586/" title="Tony Kaye (dir.), Edward Norton, Edward Furlong">American History X</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       39.
       <a href="/title/tt0407887/" title="Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon">The Departed</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       40.
       <a href="/title/tt0114814/" title="Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne">The Usual Suspects</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       41.
       <a href="/title/tt0482571/" title="Christopher Nolan (dir.), Christian Bale, Hugh Jackman">The Prestige</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       42.
       <a href="/title/tt2582802/" title="Damien Chazelle (dir.), Miles Teller, J.K. Simmons">Whiplash</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       43.
       <a href="/title/tt0034583/" title="Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman">Casablanca</a>
 <span class="secondaryInfo">(1942)</span>
 </td>,
 <td class="titleColumn">
       44.
       <a href="/title/tt0056058/" title="Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama">Seppuku</a>
 <span class="secondaryInfo">(1962)</span>
 </td>,
 <td class="titleColumn">
       45.
       <a href="/title/tt0095327/" title="Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi">Hotaru no haka</a>
 <span class="secondaryInfo">(1988)</span>
 </td>,
 <td class="titleColumn">
       46.
       <a href="/title/tt1675434/" title="Olivier Nakache (dir.), François Cluzet, Omar Sy">The Intouchables</a>
 <span class="secondaryInfo">(2011)</span>
 </td>,
 <td class="titleColumn">
       47.
       <a href="/title/tt0027977/" title="Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard">Modern Times</a>
 <span class="secondaryInfo">(1936)</span>
 </td>,
 <td class="titleColumn">
       48.
       <a href="/title/tt0064116/" title="Sergio Leone (dir.), Henry Fonda, Charles Bronson">Once Upon a Time in the West</a>
 <span class="secondaryInfo">(1968)</span>
 </td>,
 <td class="titleColumn">
       49.
       <a href="/title/tt0047396/" title="Alfred Hitchcock (dir.), James Stewart, Grace Kelly">Rear Window</a>
 <span class="secondaryInfo">(1954)</span>
 </td>,
 <td class="titleColumn">
       50.
       <a href="/title/tt0095765/" title="Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale">Nuovo Cinema Paradiso</a>
 <span class="secondaryInfo">(1988)</span>
 </td>,
 <td class="titleColumn">
       51.
       <a href="/title/tt0078748/" title="Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt">Alien</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       52.
       <a href="/title/tt0021749/" title="Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill">City Lights</a>
 <span class="secondaryInfo">(1931)</span>
 </td>,
 <td class="titleColumn">
       53.
       <a href="/title/tt0078788/" title="Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando">Apocalypse Now</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       54.
       <a href="/title/tt0209144/" title="Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss">Memento</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       55.
       <a href="/title/tt1853728/" title="Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz">Django Unchained</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       56.
       <a href="/title/tt0082971/" title="Steven Spielberg (dir.), Harrison Ford, Karen Allen">Raiders of the Lost Ark</a>
 <span class="secondaryInfo">(1981)</span>
 </td>,
 <td class="titleColumn">
       57.
       <a href="/title/tt0910970/" title="Andrew Stanton (dir.), Ben Burtt, Elissa Knight">WALL·E</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       58.
       <a href="/title/tt0405094/" title="Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck">The Lives of Others</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       59.
       <a href="/title/tt0043014/" title="Billy Wilder (dir.), William Holden, Gloria Swanson">Sunset Blvd.</a>
 <span class="secondaryInfo">(1950)</span>
 </td>,
 <td class="titleColumn">
       60.
       <a href="/title/tt0050825/" title="Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker">Paths of Glory</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       61.
       <a href="/title/tt0081505/" title="Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall">The Shining</a>
 <span class="secondaryInfo">(1980)</span>
 </td>,
 <td class="titleColumn">
       62.
       <a href="/title/tt0032553/" title="Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard">The Great Dictator</a>
 <span class="secondaryInfo">(1940)</span>
 </td>,
 <td class="titleColumn">
       63.
       <a href="/title/tt4154756/" title="Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth">Avengers: Infinity War</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       64.
       <a href="/title/tt0051201/" title="Billy Wilder (dir.), Tyrone Power, Marlene Dietrich">Witness for the Prosecution</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       65.
       <a href="/title/tt0090605/" title="James Cameron (dir.), Sigourney Weaver, Michael Biehn">Aliens</a>
 <span class="secondaryInfo">(1986)</span>
 </td>,
 <td class="titleColumn">
       66.
       <a href="/title/tt4633694/" title="Bob Persichetti (dir.), Shameik Moore, Jake Johnson">Spider-Man: Into the Spider-Verse</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       67.
       <a href="/title/tt0169547/" title="Sam Mendes (dir.), Kevin Spacey, Annette Bening">American Beauty</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       68.
       <a href="/title/tt0057012/" title="Stanley Kubrick (dir.), Peter Sellers, George C. Scott">Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb</a>
 <span class="secondaryInfo">(1964)</span>
 </td>,
 <td class="titleColumn">
       69.
       <a href="/title/tt1345836/" title="Christopher Nolan (dir.), Christian Bale, Tom Hardy">The Dark Knight Rises</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       70.
       <a href="/title/tt0364569/" title="Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-tae">Oldeuboi</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       71.
       <a href="/title/tt0361748/" title="Quentin Tarantino (dir.), Brad Pitt, Diane Kruger">Inglourious Basterds</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       72.
       <a href="/title/tt0086879/" title="Milos Forman (dir.), F. Murray Abraham, Tom Hulce">Amadeus</a>
 <span class="secondaryInfo">(1984)</span>
 </td>,
 <td class="titleColumn">
       73.
       <a href="/title/tt2380307/" title="Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal">Coco</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       74.
       <a href="/title/tt0114709/" title="John Lasseter (dir.), Tom Hanks, Tim Allen">Toy Story</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       75.
       <a href="/title/tt7286456/" title="Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro">Joker</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       76.
       <a href="/title/tt0112573/" title="Mel Gibson (dir.), Mel Gibson, Sophie Marceau">Braveheart</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       77.
       <a href="/title/tt0082096/" title="Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer">Das Boot</a>
 <span class="secondaryInfo">(1981)</span>
 </td>,
 <td class="titleColumn">
       78.
       <a href="/title/tt4154796/" title="Anthony Russo (dir.), Robert Downey Jr., Chris Evans">Avengers: Endgame</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       79.
       <a href="/title/tt0119698/" title="Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida">Mononoke-hime</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       80.
       <a href="/title/tt0087843/" title="Sergio Leone (dir.), Robert De Niro, James Woods">Once Upon a Time in America</a>
 <span class="secondaryInfo">(1984)</span>
 </td>,
 <td class="titleColumn">
       81.
       <a href="/title/tt0119217/" title="Gus Van Sant (dir.), Robin Williams, Matt Damon">Good Will Hunting</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       82.
       <a href="/title/tt5311514/" title="Makoto Shinkai (dir.), Ryunosuke Kamiki, Mone Kamishiraishi">Kimi no na wa.</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       83.
       <a href="/title/tt0045152/" title="Stanley Donen (dir.), Gene Kelly, Donald O'Connor">Singin' in the Rain</a>
 <span class="secondaryInfo">(1952)</span>
 </td>,
 <td class="titleColumn">
       84.
       <a href="/title/tt1187043/" title="Rajkumar Hirani (dir.), Aamir Khan, Madhavan">3 Idiots</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       85.
       <a href="/title/tt0180093/" title="Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto">Requiem for a Dream</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       86.
       <a href="/title/tt0057565/" title="Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada">Tengoku to jigoku</a>
 <span class="secondaryInfo">(1963)</span>
 </td>,
 <td class="titleColumn">
       87.
       <a href="/title/tt0435761/" title="Lee Unkrich (dir.), Tom Hanks, Tim Allen">Toy Story 3</a>
 <span class="secondaryInfo">(2010)</span>
 </td>,
 <td class="titleColumn">
       88.
       <a href="/title/tt8267604/" title="Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw">Capharnaüm</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       89.
       <a href="/title/tt0086190/" title="Richard Marquand (dir.), Mark Hamill, Harrison Ford">Star Wars: Episode VI - Return of the Jedi</a>
 <span class="secondaryInfo">(1983)</span>
 </td>,
 <td class="titleColumn">
       90.
       <a href="/title/tt0338013/" title="Michel Gondry (dir.), Jim Carrey, Kate Winslet">Eternal Sunshine of the Spotless Mind</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       91.
       <a href="/title/tt0062622/" title="Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood">2001: A Space Odyssey</a>
 <span class="secondaryInfo">(1968)</span>
 </td>,
 <td class="titleColumn">
       92.
       <a href="/title/tt0105236/" title="Quentin Tarantino (dir.), Harvey Keitel, Tim Roth">Reservoir Dogs</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       93.
       <a href="/title/tt0091251/" title="Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova">Idi i smotri</a>
 <span class="secondaryInfo">(1985)</span>
 </td>,
 <td class="titleColumn">
       94.
       <a href="/title/tt2106476/" title="Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen">Jagten</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       95.
       <a href="/title/tt0033467/" title="Orson Welles (dir.), Orson Welles, Joseph Cotten">Citizen Kane</a>
 <span class="secondaryInfo">(1941)</span>
 </td>,
 <td class="titleColumn">
       96.
       <a href="/title/tt0022100/" title="Fritz Lang (dir.), Peter Lorre, Ellen Widmann">M - Eine Stadt sucht einen Mörder</a>
 <span class="secondaryInfo">(1931)</span>
 </td>,
 <td class="titleColumn">
       97.
       <a href="/title/tt0056172/" title="David Lean (dir.), Peter O'Toole, Alec Guinness">Lawrence of Arabia</a>
 <span class="secondaryInfo">(1962)</span>
 </td>,
 <td class="titleColumn">
       98.

In [7]:
names[0].a.text

'The Shawshank Redemption'

In [11]:
re.search('\d+', names[0].span.text)[0]

'1994'

In [12]:
ratings = soup.find_all('td', class_ = 'ratingColumn imdbRating')
ratings

[<td class="ratingColumn imdbRating">
 <strong title="9.2 based on 2,706,500 user ratings">9.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.2 based on 1,879,480 user ratings">9.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.0 based on 2,679,924 user ratings">9.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.0 based on 1,283,440 user ratings">9.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.0 based on 799,551 user ratings">9.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 1,367,747 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 1,863,125 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 2,077,873 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 1,892,594 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 768,437 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 2,102,851 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 2,150,976 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 1,682,334 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 2,377,927 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 1,303,985 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 1,931,207 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 1,173,959 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,016,117 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,671,211 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 349,061 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 467,170 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,447,084 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,404,690 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 762,928 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,864,885 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 702,481 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,315,690 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,376,379 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,109,521 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,219,292 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 774,477 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 842,331 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 678,546 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 825,493 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,173,433 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,069,696 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,515,080 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,131,687 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,337,927 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,093,895 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,346,541 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 881,060 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 576,971 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 59,150 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 281,884 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 868,841 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 245,388 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 333,397 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 496,464 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 264,540 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 891,741 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 186,678 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 674,359 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,249,426 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,573,617 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 975,307 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,127,502 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 392,980 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 224,413 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 199,805 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,033,928 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 226,375 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,098,490 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 127,457 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 724,644 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 543,538 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,162,903 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 495,418 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,720,367 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 587,081 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,467,730 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 405,294 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 519,920 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,004,156 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,315,546 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,045,723 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 253,267 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,151,875 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 400,139 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 355,987 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 985,380 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 275,791 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 245,907 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 405,398 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 851,198 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 46,568 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 844,541 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 92,577 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,063,584 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,018,628 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 676,253 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,029,514 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 82,847 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 335,641 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 446,092 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 159,941 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 297,363 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 331,436 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 80,095 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 406,522 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 184,178 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 762,919 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 838,111 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 159,160 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 749,829 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 852,392 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 98,150 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 534,618 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 180,822 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 319,327 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 663,501 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 266,296 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,054,873 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 247,263 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 176,432 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 846,157 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 587,770 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 892,795 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 864,533 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 762,548 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 165,555 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 195,740 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 605,142 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 359,130 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 194,370 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 259,883 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,484,667 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 127,944 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 270,459 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 160,851 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 132,640 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,434,218 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 504,123 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 78,694 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 527,254 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 127,366 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 675,022 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,097,810 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 594,201 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 416,137 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,000,765 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,335,550 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 940,558 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,000,078 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 124,410 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 126,345 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 546,708 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 247,216 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 986,287 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,126,840 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 170,728 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 773,481 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 431,732 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,053,801 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 244,657 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 330,863 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 358,463 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,130,620 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 319,020 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 588,668 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 724,053 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 178,339 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 212,041 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 402,654 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 516,940 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 223,251 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 694,046 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 730,179 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 477,474 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 685,363 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 782,318 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 345,751 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,000,315 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 693,351 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 75,708 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 778,563 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 112,709 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 314,770 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 162,479 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 708,154 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">

In [14]:
ratings[0].text.strip()

'9.2'

In [16]:
title_list = []
year_list = []
rating_list = []

for i in range(len(names)):
    title_list.append(names[i].a.text)
    year_list.append(int(re.search('\d+', names[i].span.text)[0]))
    rating_list.append(float(ratings[i].text.strip()))
    
df = pd.DataFrame({'Title':title_list, 'Year':year_list, 'Rating':rating_list})
df

                        Title  Year  Rating
0    The Shawshank Redemption  1994     9.2
1               The Godfather  1972     9.2
2             The Dark Knight  2008     9.0
3       The Godfather Part II  1974     9.0
4                12 Angry Men  1957     9.0
..                        ...   ...     ...
245               Dersu Uzala  1975     8.0
246                  The Help  2011     8.0
247                   Aladdin  1992     8.0
248                    Gandhi  1982     8.0
249        Dances with Wolves  1990     8.0

[250 rows x 3 columns]

In [17]:
df.to_csv('Top_250_movies.csv', index = False)